---
  - name: install web components
    apt: name={{item}} state=present update_cache=yes
    with_items:
        - openjdk-11-jdk

  - name: Apply Page Template
    template:
      src: zookeeper.service.j2
      dest: /etc/systemd/system/zookeeper.service
      mode: 0644
      notify: 
        - reload systemd
        - restart zookeeper


  - name: Create Group
    group:
      name: "{{group}}"
      state: present

  - name: Create User
    user:
      name: "{{user}}"
      group: "{{group}}"
      state: present

  - name: Download zookeeper
    get_url:
      url: https://dlcdn.apache.org/zookeeper/zookeeper-{{version}}/apache-zookeeper-{{version}}-bin.tar.gz
      dest: /usr/local/src/ mode 0755

  - name: Create Directory
    file:
      path: /opt/zookeeper/{{version}}
      state: directory

  - name: Extract
    unarchive:
      src: /usr/local/src/apache-zookeeper-{{version}}-bin.tar.gz
      dest: /opt/zookeeper/{{version}}
      extra_opts: [--strip-components=1] 
      mode: 0755

  - name: Create Data Directory
    file:
      path: "{{data_dir}}"
      owner: "{{user}}"
      group: "{{group}}"
      mode: 0755
      state: directory

  - name: Create Log Directory
    file:
      path: "{{log_dir}}"
      owner: "{{user}}"
      group: "{{group}}"
      mode: 0755
      state: directory
