---
  - name: install web components
    apt: name={{item}} state=present
    with_items:
        - openjdk-11-jdk


  - name: Create Group
    group:
      name: "{{group}}"
      state: present

  - name: Create User
    user:
      name: "{{user}}"
      group: "{{group}}"
      state: present

  - name: Download zookeeper
    get_url:
      url: https://dlcdn.apache.org/zookeeper/zookeeper-{{version}}/apache-zookeeper-{{version}}-bin.tar.gz
      dest: /usr/local/src/ mode 0755

  - name: Create Directory
    file:
      path: /opt/zookeeper/{{version}}
      state: directory 
      mode: 0755 
      recurse: yes

  - name: Extract
    unarchive:
      src: /usr/local/src/apache-zookeeper-{{version}}-bin.tar.gz
      dest: /opt/zookeeper/{{version}}
      extra_opts: [--strip-components=1] 
      mode: 0755

  - name: Create Data Directory
    file:
      path: "{{data_dir}}"
      owner: "{{user}}"
      group: "{{group}}"
      mode: 0755
      state: directory

  - name: Create Log Directory
    file:
      path: "{{log_dir}}"
      owner: "{{user}}"
      group: "{{group}}"
      mode: 0755
      state: directory


  - name: Config Files Setup
    template:
      src: zoo.cfg.j2
      dest: /opt/zookeeper/{{version}}/conf/zoo.cfg 
      mode: 0755

  - name: myid Template Setup
    template:
      src: myid.j2
      dest: "{{data_dir}}/myid"
      owner: "{{user}}"
      group: "{{group}}"
      mode: 0755
      

  - name: Overwrite myid file.
    template: src=myid.j2 dest={{data_dir}}/myid force="{{ zookeeper_force_myid }}"

  - name: Apply systemctl Template
    template:
      src: zookeeper.service.j2
      dest: /etc/systemd/system/zookeeper.service
      mode: 0755

  - name: reload systemd
    become: true
    command: systemctl daemon-reload

  - name: Change Ownership
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{user}}"
      group: "{{group}}"
      mode: 0755
      recurse: true
    with_items:
        - /opt/zookeeper/
        - /data/zookeeper/
        - /log/zookeeper/


  - name: Start Zookeeper
    ansible.builtin.systemd:
      name: zookeeper.service
      state: started
    register: zookeeper_service_status

  - debug: 
      var: zookeeper_service_status.ActiveState