---
user: zookeeper
group: zookeeper
data_dir: /data/zookeeper/
log_dir: /log/zookeeper/
version: 3.7.1
zookeeper_cluster_ports: "2888:3888"
zookeeper_hosts_hostname: "{{inventory_hostname}}"
zookeeper_hosts:
  - host: "{{zookeeper_hosts_hostname}}"
    id: 1
zookeeper_force_myid: yes